#!/usr/bin/env python3
"""Generate kernel/_error_codes_generated.py from error-codes.yaml."""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
YAML_PATH = Path(__file__).resolve().parent / "error-codes.yaml"
OUT_PATH = ROOT / "src" / "jarvis" / "kernel" / "_error_codes_generated.py"


def main() -> int:
    if not YAML_PATH.exists():
        print(f"Missing {YAML_PATH}", file=sys.stderr)
        return 1

    raw = yaml.safe_load(YAML_PATH.read_text(encoding="utf-8")) or {}
    codes = sorted(raw.keys())

    lines = [
        "# AUTO-GENERATED by scripts/error_audit/generate_registry.py — do not edit.",
        "# ruff: noqa: E501",
        "from __future__ import annotations",
        "",
        "from typing import TypedDict",
        "",
        "",
        "class ErrorSpec(TypedDict, total=False):",
        "    domain: str",
        "    severity: str",
        "    title_fr: str",
        "    message_fr: str",
        "    resolution_fr: str",
        "    docs: list[str]",
        "    since: str",
        "    modules: list[str]",
        "",
        "",
        "ERROR_REGISTRY: dict[str, ErrorSpec] = {",
    ]

    for code in codes:
        spec = raw[code]
        lines.append(f'    "{code}": {{')
        for key, val in spec.items():
            if isinstance(val, str):
                lines.append(f'        "{key}": {val!r},')
            elif isinstance(val, list):
                items = ", ".join(repr(x) for x in val)
                lines.append(f'        "{key}": [{items}],')
        lines.append("    },")

    lines += [
        "}",
        "",
        "ALL_CODES: frozenset[str] = frozenset(ERROR_REGISTRY.keys())",
        "",
    ]

    OUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Generated {OUT_PATH} ({len(codes)} codes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
